ㅇㅇ

diff --git a/3.10/gradlew b/3.10/gradlew
--- a/3.10/gradlew
+++ b/3.10/gradlew
@@ -32,8 +32,8 @@
 #       Busybox and similar reduced shells will NOT work, because this script
 #       requires all of these POSIX shell features:
 #         * functions;
-#         * expansions «#[[\$]]#var», «#[[\$]]#{var}», «#[[\$]]#{var:-default}», «#[[\$]]#{var+SET}»,
-#           «#[[\$]]#{var#prefix}», «#[[\$]]#{var%suffix}», and «#[[\$]]#( cmd )»;
+#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
+#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
 #         * compound commands having a testable exit status, especially «case»;
 #         * various built-in commands including «command», «set», and «ulimit».
 #
@@ -45,7 +45,7 @@
 #       The "traditional" practice of packing multiple parameters into a
 #       space-separated string is a well documented source of bugs and security
 #       problems, so this is (mostly) avoided, by progressively accumulating
-#       options in "#[[\$]]#@", and eventually passing that to Java.
+#       options in "$@", and eventually passing that to Java.
 #
 #       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
 #       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
@@ -55,7 +55,7 @@
 #       Darwin, MinGW, and NonStop.
 #
 #   (3) This script is generated from the Groovy template
-#       https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
 #       within the Gradle project.
 #
 #       You can find Gradle at https://github.com/gradle/gradle/.
@@ -64,26 +64,26 @@
 
 # Attempt to set APP_HOME
 
-# Resolve links: #[[\$]]#0 may be a link
-app_path=#[[\$]]#0
+# Resolve links: $0 may be a link
+app_path=$0
 
 # Need this for daisy-chained symlinks.
 while
-    APP_HOME=#[[\$]]#{app_path%"#[[\$]]#{app_path##*/}"}  # leaves a trailing /; empty if no leading path
-    [ -h "#[[\$]]#app_path" ]
+    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
+    [ -h "$app_path" ]
 do
-    ls=#[[\$]]#( ls -ld "#[[\$]]#app_path" )
-    link=#[[\$]]#{ls#*' -> '}
-    case #[[\$]]#link in             #(
-      /*)   app_path=#[[\$]]#link ;; #(
-      *)    app_path=#[[\$]]#APP_HOME#[[\$]]#link ;;
+    ls=$( ls -ld "$app_path" )
+    link=${ls#*' -> '}
+    case $link in             #(
+      /*)   app_path=$link ;; #(
+      *)    app_path=$APP_HOME$link ;;
     esac
 done
 
-APP_HOME=#[[\$]]#( cd "#[[\$]]#{APP_HOME:-./}" && pwd -P ) || exit
-
-APP_NAME="Gradle"
-APP_BASE_NAME=#[[\$]]#{0##*/}
+# This is normally unused
+# shellcheck disable=SC2034
+APP_BASE_NAME=${0##*/}
+APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
 
 # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
 DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
@@ -92,12 +92,12 @@ DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
 MAX_FD=maximum
 
 warn () {
-    echo "#[[\$]]#*"
+    echo "$*"
 } >&2
 
 die () {
     echo
-    echo "#[[\$]]#*"
+    echo "$*"
     echo
     exit 1
 } >&2
@@ -107,26 +107,26 @@ cygwin=false
 msys=false
 darwin=false
 nonstop=false
-case "#[[\$]]#( uname )" in                #(
+case "$( uname )" in                #(
   CYGWIN* )         cygwin=true  ;; #(
   Darwin* )         darwin=true  ;; #(
   MSYS* | MINGW* )  msys=true    ;; #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-CLASSPATH=#[[\$]]#APP_HOME/gradle/wrapper/gradle-wrapper.jar
+CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
 
 
 # Determine the Java command to use to start the JVM.
-if [ -n "#[[\$]]#JAVA_HOME" ] ; then
-    if [ -x "#[[\$]]#JAVA_HOME/jre/sh/java" ] ; then
+if [ -n "$JAVA_HOME" ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
         # IBM's JDK on AIX uses strange locations for the executables
-        JAVACMD=#[[\$]]#JAVA_HOME/jre/sh/java
+        JAVACMD=$JAVA_HOME/jre/sh/java
     else
-        JAVACMD=#[[\$]]#JAVA_HOME/bin/java
+        JAVACMD=$JAVA_HOME/bin/java
     fi
-    if [ ! -x "#[[\$]]#JAVACMD" ] ; then
-        die "ERROR: JAVA_HOME is set to an invalid directory: #[[\$]]#JAVA_HOME
+    if [ ! -x "$JAVACMD" ] ; then
+        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
@@ -140,17 +140,21 @@ location of your Java installation."
 fi
 
 # Increase the maximum file descriptors if we can.
-if ! "#[[\$]]#cygwin" && ! "#[[\$]]#darwin" && ! "#[[\$]]#nonstop" ; then
-    case #[[\$]]#MAX_FD in #(
+if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
+    case $MAX_FD in #(
       max*)
-        MAX_FD=#[[\$]]#( ulimit -H -n ) ||
+        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC3045 
+        MAX_FD=$( ulimit -H -n ) ||
             warn "Could not query maximum file descriptor limit"
     esac
-    case #[[\$]]#MAX_FD in  #(
+    case $MAX_FD in  #(
       '' | soft) :;; #(
       *)
-        ulimit -n "#[[\$]]#MAX_FD" ||
-            warn "Could not set maximum file descriptor limit to #[[\$]]#MAX_FD"
+        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC3045 
+        ulimit -n "$MAX_FD" ||
+            warn "Could not set maximum file descriptor limit to $MAX_FD"
     esac
 fi
 
@@ -163,23 +167,23 @@ fi
 #   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.
 
 # For Cygwin or MSYS, switch paths to Windows format before running java
-if "#[[\$]]#cygwin" || "#[[\$]]#msys" ; then
-    APP_HOME=#[[\$]]#( cygpath --path --mixed "#[[\$]]#APP_HOME" )
-    CLASSPATH=#[[\$]]#( cygpath --path --mixed "#[[\$]]#CLASSPATH" )
+if "$cygwin" || "$msys" ; then
+    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
+    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
 
-    JAVACMD=#[[\$]]#( cygpath --unix "#[[\$]]#JAVACMD" )
+    JAVACMD=$( cygpath --unix "$JAVACMD" )
 
     # Now convert the arguments - kludge to limit ourselves to /bin/sh
     for arg do
         if
-            case #[[\$]]#arg in                                #(
+            case $arg in                                #(
               -*)   false ;;                            # don't mess with options #(
-              /?*)  t=#[[\$]]#{arg#/} t=/#[[\$]]#{t%%/*}              # looks like a POSIX filepath
-                    [ -e "#[[\$]]#t" ] ;;                      #(
+              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
+                    [ -e "$t" ] ;;                      #(
               *)    false ;;
             esac
         then
-            arg=#[[\$]]#( cygpath --path --ignore --mixed "#[[\$]]#arg" )
+            arg=$( cygpath --path --ignore --mixed "$arg" )
         fi
         # Roll the args list around exactly as many times as the number of
         # args, so each arg winds up back in the position where it started, but
@@ -189,21 +193,21 @@ if "#[[\$]]#cygwin" || "#[[\$]]#msys" ; then
         # changing the positional parameters here affects neither the number of
         # iterations, nor the values presented in `arg`.
         shift                   # remove old arg
-        set -- "#[[\$]]#@" "#[[\$]]#arg"      # push replacement arg
+        set -- "$@" "$arg"      # push replacement arg
     done
 fi
 
 # Collect all arguments for the java command;
-#   * #[[\$]]#DEFAULT_JVM_OPTS, #[[\$]]#JAVA_OPTS, and #[[\$]]#GRADLE_OPTS can contain fragments of
+#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
 #     shell script including quotes and variable substitutions, so put them in
 #     double quotes to make sure that they get re-expanded; and
 #   * put everything else in single quotes, so that it's not re-expanded.
 
 set -- \
-        "-Dorg.gradle.appname=#[[\$]]#APP_BASE_NAME" \
-        -classpath "#[[\$]]#CLASSPATH" \
+        "-Dorg.gradle.appname=$APP_BASE_NAME" \
+        -classpath "$CLASSPATH" \
         org.gradle.wrapper.GradleWrapperMain \
-        "#[[\$]]#@"
+        "$@"
 
 # Stop when "xargs" is not available.
 if ! command -v xargs >/dev/null 2>&1
@@ -217,8 +221,8 @@ fi
 #
 # In Bash we could simply go:
 #
-#   readarray ARGS < <( xargs -n1 <<<"#[[\$]]#var" ) &&
-#   set -- "#[[\$]]#{ARGS[@]}" "#[[\$]]#@"
+#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
+#   set -- "${ARGS[@]}" "$@"
 #
 # but POSIX shell has neither arrays nor command substitution, so instead we
 # post-process each arg (as a line of input to sed) to backslash-escape any
@@ -230,11 +234,11 @@ fi
 # an unmatched quote.
 #
 
-eval "set -- #[[\$]]#(
-        printf '%s\n' "#[[\$]]#DEFAULT_JVM_OPTS #[[\$]]#JAVA_OPTS #[[\$]]#GRADLE_OPTS" |
+eval "set -- $(
+        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
         xargs -n1 |
         sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
         tr '\n' ' '
-    )" '"#[[\$]]#@"'
+    )" '"$@"'
 
-exec "#[[\$]]#JAVACMD" "#[[\$]]#@"
+exec "$JAVACMD" "$@"
